// Auto-generated by RPG Generator
// Generated on: 2025-08-16T17:09:02.211Z

export interface Map {
  id: number;
  name: string;
  description: string;
  minLevel: number;
  recommendedLevel: number;
}

export const MAPS: Map[] = [
  {
    id: 1,
    name: 'Venom River',
    description: 'A place where time itself seems to stand still.',
    minLevel: 1,
    recommendedLevel: 2,
  },
  {
    id: 2,
    name: 'Golden Valley',
    description: 'A place where time itself seems to stand still.',
    minLevel: 5,
    recommendedLevel: 6,
  },
  {
    id: 3,
    name: 'Spirit Temple',
    description: 'A place where reality bends and twists.',
    minLevel: 10,
    recommendedLevel: 12,
  },
  {
    id: 4,
    name: 'Light Cave',
    description: 'Where the brave go to prove their worth.',
    minLevel: 15,
    recommendedLevel: 18,
  },
  {
    id: 5,
    name: 'Silver Forest',
    description: 'Home to creatures of legend and myth.',
    minLevel: 20,
    recommendedLevel: 24,
  },
  {
    id: 6,
    name: 'Golden Plains',
    description: 'Home to creatures of legend and myth.',
    minLevel: 25,
    recommendedLevel: 30,
  },
  {
    id: 7,
    name: 'Spirit Forest',
    description: 'A realm of darkness and forgotten treasures.',
    minLevel: 30,
    recommendedLevel: 36,
  },
  {
    id: 8,
    name: 'Spirit Forest',
    description: 'Home to creatures of legend and myth.',
    minLevel: 35,
    recommendedLevel: 42,
  },
  {
    id: 9,
    name: 'Chaos Cave',
    description: 'Ancient forces still linger in these halls.',
    minLevel: 40,
    recommendedLevel: 48,
  },
];

export default MAPS;
