// Auto-generated by Equipment Generator
// Generated on: 2025-08-17T05:51:58.163Z

export const EQUIPMENT_CONFIG = {
  rarityMultipliers: {
    common: {
      min: 1,
      base: 2,
      max: 3,
    },
    uncommon: {
      min: 2,
      base: 3,
      max: 4,
    },
    rare: {
      min: 3,
      base: 4,
      max: 5,
    },
    epic: {
      min: 4,
      base: 5,
      max: 6,
    },
    legendary: {
      min: 6,
      base: 8,
      max: 10,
    },
  },
  priceMultipliers: {
    common: {
      min: 50,
      base: 100,
      max: 150,
    },
    uncommon: {
      min: 150,
      base: 250,
      max: 350,
    },
    rare: {
      min: 400,
      base: 600,
      max: 800,
    },
    epic: {
      min: 1000,
      base: 1500,
      max: 2000,
    },
    legendary: {
      min: 3000,
      base: 4000,
      max: 5000,
    },
  },
  levelPriceScaling: {
    '1': 1,
    '5': 1.5,
    '10': 2.5,
    '15': 4,
    '20': 6,
    '25': 9,
    '30': 13,
    '35': 18,
    '40': 25,
  },
  dropRateMultipliers: {
    common: {
      min: 0.08,
      base: 0.1,
      max: 0.12,
    },
    uncommon: {
      min: 0.06,
      base: 0.08,
      max: 0.1,
    },
    rare: {
      min: 0.04,
      base: 0.06,
      max: 0.08,
    },
    epic: {
      min: 0.02,
      base: 0.04,
      max: 0.06,
    },
    legendary: {
      min: 0.01,
      base: 0.02,
      max: 0.03,
    },
  },
} as const;

// Equipment type configurations
export const EQUIPMENT_TYPES = [
  {
    type: 'weapon',
    namePrefixes: [
      'Iron',
      'Steel',
      'Mithril',
      'Adamantine',
      'Dragonbone',
      'Celestial',
      'Void',
      'Ethereal',
      'Ancient',
      'Mystic',
    ],
    nameSuffixes: [
      'Sword',
      'Axe',
      'Mace',
      'Bow',
      'Staff',
      'Wand',
      'Dagger',
      'Hammer',
      'Spear',
      'Crossbow',
    ],
    descriptionTemplates: [
      'A {rarity} {type} that enhances your combat prowess.',
      'This {rarity} {type} has been crafted with precision.',
      'A legendary {type} that has seen countless battles.',
      'The {rarity} {type} pulses with magical energy.',
      'Forged from the finest materials, this {type} is truly {rarity}.',
    ],
  },
  {
    type: 'armor',
    namePrefixes: [
      'Leather',
      'Chain',
      'Plate',
      'Scale',
      'Dragonhide',
      'Celestial',
      'Void',
      'Ethereal',
      'Ancient',
      'Mystic',
    ],
    nameSuffixes: [
      'Helmet',
      'Chestplate',
      'Greaves',
      'Gauntlets',
      'Boots',
      'Shield',
      'Cuirass',
      'Pauldrons',
      'Vambraces',
      'Sabatons',
    ],
    descriptionTemplates: [
      'A {rarity} {type} that provides excellent protection.',
      'This {rarity} {type} has been reinforced with magic.',
      'A legendary {type} that has withstood the test of time.',
      'The {rarity} {type} glows with protective enchantments.',
      'Crafted by master artisans, this {type} is truly {rarity}.',
    ],
  },
  {
    type: 'accessory',
    namePrefixes: [
      'Ring',
      'Amulet',
      'Bracelet',
      'Necklace',
      'Crown',
      'Tiara',
      'Belt',
      'Cloak',
      'Cape',
      'Mantle',
    ],
    nameSuffixes: [
      'of Power',
      'of Protection',
      'of Speed',
      'of Wisdom',
      'of Fortune',
      'of the Warrior',
      'of the Mage',
      'of the Archer',
      'of the Guardian',
      'of the Assassin',
    ],
    descriptionTemplates: [
      'A {rarity} {type} that enhances your abilities.',
      'This {rarity} {type} has been blessed with magic.',
      'A legendary {type} that has been passed down through generations.',
      'The {rarity} {type} radiates with mystical power.',
      'Crafted by ancient masters, this {type} is truly {rarity}.',
    ],
  },
] as const;

// Equipment levels to generate
export const EQUIPMENT_LEVELS = [1, 5, 10, 15, 20, 25, 30, 35, 40] as const;

// Rarities to generate
export const EQUIPMENT_RARITIES = [
  'common',
  'uncommon',
  'rare',
  'epic',
  'legendary',
] as const;
