import type { Monster } from '~/types/monster';

export const MONSTERS: Monster[] = [
  // Forest of Eldoria (minLevel: 1)
  {
    id: 1,
    mapId: 1,
    name: 'Goblin',
    description: 'A small, green creature with a pointy hat.',
    level: 1,
    experience: 100,
    gold: 10,
    health: 80,
    attack: 8,
    defense: 5,
    speed: 12,
    critical: 8,
  },
  {
    id: 2,
    mapId: 1,
    name: 'Wolf',
    description: 'A fierce wolf with sharp fangs and keen senses.',
    level: 2,
    experience: 150,
    gold: 15,
    health: 100,
    attack: 12,
    defense: 6,
    speed: 15,
    critical: 10,
  },
  {
    id: 3,
    mapId: 1,
    name: 'Bandit',
    description: 'A desperate thief armed with a rusty dagger.',
    level: 3,
    experience: 200,
    gold: 25,
    health: 120,
    attack: 15,
    defense: 8,
    speed: 13,
    critical: 12,
  },

  // Desert of Kalandra (minLevel: 2)
  {
    id: 4,
    mapId: 2,
    name: 'Scorpion',
    description: 'A deadly desert scorpion with a venomous stinger.',
    level: 2,
    experience: 150,
    gold: 20,
    health: 90,
    attack: 18,
    defense: 4,
    speed: 16,
    critical: 15,
  },
  {
    id: 5,
    mapId: 2,
    name: 'Desert Bandit',
    description: 'A hardened outlaw who roams the scorching sands.',
    level: 3,
    experience: 200,
    gold: 30,
    health: 130,
    attack: 20,
    defense: 10,
    speed: 14,
    critical: 12,
  },
  {
    id: 6,
    mapId: 2,
    name: 'Sand Golem',
    description: 'A massive construct made of hardened desert sand.',
    level: 4,
    experience: 300,
    gold: 40,
    health: 200,
    attack: 22,
    defense: 25,
    speed: 8,
    critical: 5,
  },

  // Mountains of Aethel (minLevel: 5)
  {
    id: 7,
    mapId: 3,
    name: 'Mountain Troll',
    description: 'A hulking troll with stone-like skin.',
    level: 5,
    experience: 400,
    gold: 60,
    health: 300,
    attack: 35,
    defense: 30,
    speed: 10,
    critical: 8,
  },
  {
    id: 8,
    mapId: 3,
    name: 'Ice Drake',
    description: 'A young dragon with frost breath and icy scales.',
    level: 6,
    experience: 500,
    gold: 80,
    health: 350,
    attack: 40,
    defense: 25,
    speed: 18,
    critical: 15,
  },
  {
    id: 9,
    mapId: 3,
    name: 'Yeti',
    description: 'A massive white-furred creature of the mountains.',
    level: 7,
    experience: 600,
    gold: 100,
    health: 400,
    attack: 45,
    defense: 35,
    speed: 12,
    critical: 10,
  },

  // Swamp of Mire (minLevel: 10)
  {
    id: 10,
    mapId: 4,
    name: 'Swamp Witch',
    description:
      'A corrupted spellcaster who draws power from the murky waters.',
    level: 10,
    experience: 800,
    gold: 150,
    health: 450,
    attack: 55,
    defense: 20,
    speed: 20,
    critical: 25,
  },
  {
    id: 11,
    mapId: 4,
    name: 'Giant Crocodile',
    description: 'A massive reptile lurking in the swamp waters.',
    level: 11,
    experience: 900,
    gold: 180,
    health: 500,
    attack: 60,
    defense: 40,
    speed: 15,
    critical: 12,
  },
  {
    id: 12,
    mapId: 4,
    name: 'Plague Bearer',
    description: 'A diseased creature spreading corruption through the swamp.',
    level: 12,
    experience: 1000,
    gold: 200,
    health: 550,
    attack: 65,
    defense: 25,
    speed: 18,
    critical: 20,
  },

  // Plains of Arathia (minLevel: 12)
  {
    id: 13,
    mapId: 5,
    name: 'Centaur Warrior',
    description: 'A skilled half-horse, half-human warrior with a mighty bow.',
    level: 12,
    experience: 1000,
    gold: 200,
    health: 500,
    attack: 70,
    defense: 30,
    speed: 25,
    critical: 22,
  },
  {
    id: 14,
    mapId: 5,
    name: 'Griffin',
    description:
      'A majestic beast with the body of a lion and wings of an eagle.',
    level: 13,
    experience: 1100,
    gold: 250,
    health: 600,
    attack: 75,
    defense: 35,
    speed: 30,
    critical: 18,
  },
  {
    id: 15,
    mapId: 5,
    name: 'Ancient Guardian',
    description: 'A mystical protector of the plains with ethereal powers.',
    level: 14,
    experience: 1200,
    gold: 300,
    health: 650,
    attack: 80,
    defense: 45,
    speed: 22,
    critical: 25,
  },

  // City of Eldoria (minLevel: 17)
  {
    id: 16,
    mapId: 6,
    name: 'Dark Assassin',
    description: 'A shadowy killer who strikes from the darkness.',
    level: 17,
    experience: 1500,
    gold: 400,
    health: 700,
    attack: 90,
    defense: 30,
    speed: 35,
    critical: 30,
  },
  {
    id: 17,
    mapId: 6,
    name: 'Corrupted Knight',
    description: 'A fallen warrior whose armor is tainted with dark magic.',
    level: 18,
    experience: 1600,
    gold: 450,
    health: 750,
    attack: 95,
    defense: 50,
    speed: 25,
    critical: 20,
  },
  {
    id: 18,
    mapId: 6,
    name: 'Shadow Lord',
    description:
      'A powerful entity of pure darkness that haunts the city streets.',
    level: 19,
    experience: 1700,
    gold: 500,
    health: 800,
    attack: 100,
    defense: 40,
    speed: 28,
    critical: 35,
  },
];
